FROM golang:1.5.2

MAINTAINER razr razr.china@gmail.com

RUN go get -u github.com/PandoCloud/pando-cloud

RUN go install github.com/PandoCloud/pando-cloud/services/...
RUN go install github.com/PandoCloud/pando-cloud/tools/...
RUN go install github.com/PandoCloud/pando-cloud/tests/...